version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecksumtype
    - goconst
    - gocritic
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - importas
    - inamedparam
    - ineffassign
    - intrange
    - ireturn
    - loggercheck
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - staticcheck
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    gocritic:
      disabled-checks:
        - assignOp
        - ifElseChain
        - singleCaseSwitch
        - commentFormatting
    gomoddirectives:
      replace-local: true
    gosec:
      confidence: medium
    importas:
      alias:
        - pkg: ^github.com\/foomo\/go\/(.*\/)?([^\/]+)\/?$
          alias: ${2}x
      no-unaliased: true
    misspell:
      mode: restricted
    predeclared:
      ignore:
        - new
        - error
    revive:
      enable-all-rules: true
      rules:
        - name: useless-break
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: bare-return
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: unused-parameter
          disabled: true
        - name: add-constant
          disabled: true
        - name: indent-error-flow
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: function-length
          disabled: true
        - name: var-naming
          disabled: true
        - name: use-any
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: function-result-limit
          disabled: true
        - name: flag-parameter
          disabled: true
        - name: unused-receiver
          disabled: true
        - name: argument-limit
          disabled: true
        - name: empty-lines
          disabled: true
        - name: confusing-naming
          disabled: true
        - name: import-shadowing
          disabled: true
        - name: max-control-nesting
          disabled: true
        - name: exported
          disabled: true
        - name: unnecessary-stmt
          disabled: true
        - name: comment-spacings
          disabled: true
        - name: struct-tag
          arguments:
            - json,inline
        - name: superfluous-else
          disabled: true
        - name: unexported-return
          disabled: true
        - name: package-directory-mismatch
          disabled: true
        - name: unhandled-error
          arguments:
            - fmt.Println
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - forbidigo
          - forcetypeassert
        path: _test\.go
      - linters:
          - asasalint
        path: (.+)_test\.go
    paths:
      - bin
      - tmp
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - bin
      - tmp
      - third_party$
      - builtin$
      - examples$
